---
# ============================================================
# site.yml
# Master Playbook voor het gehele DBF Homelab
# ============================================================

- name: Lokal K3s Applicaties uitrollen
  import_playbook: playbook_k3s_homelab.yml

# - name: Azure Webservers configureren
#   import_playbook: playbook_azure_webservers.yml
